(function(){
    angular.module('templeOfLearning.app',[
        'app.core',
        'app.common',
        'app.login',
        'app.schoolReg',
        'app.schoolList',
        'app.dashboard'
    ]);
})();
