(function(){
    angular.module('templeOfLearning.app',[
        'app.core',
        'app.common',
        'app.login',
        'app.school',
        'app.dashboard',
        'app.student',
        'app.widgets',
        'app.finance'
    ]);
})();
